### PR TITLE
docs(readme): add testing requirements section (from `vault-formula`)

### PR DESCRIPTION
**Pull request by myii**
* https://github.com/saltstack-formulas/vault-formula/blob/43dc95d/docs/README.rst#requirements

### CODE REVIEW

**Comment by javierbertoli** [comment]
Thanks @myii !

**Comment by myii** [comment]
Thanks for the merge.

**Comment by n-rodriguez** [comment]
I had some suggestions about this PR. I'll let you know later.

**Comment by myii** [comment]
@n-rodriguez Please, be my guest.  We can make any improvements in a new PR.

**Pull request merged**
