### PR TITLE
chore: add optional `pre-commit` configuration

### PR DESCRIPTION
**Pull request by dafyddj**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [x] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Add configuration for [`pre-commit`](https://pre-commit.com/) to allow automatic linting, some syntax checking, whitespace fixing and checking for a valid commit message prior to a successful `git commit`.

Replicates the current linting etc. run in Travis CI.

### Pillar / config required to test the proposed changes

NA

### Debug log showing how the proposed changes work

```
$ cat TEMPLATE/files/default/example.tmpl
########################################################################
# File managed by Salt at <{{ source }}>.
# Your changes will be overwritten.
########################################################################

{{ source}}

This is an example file from SaltStack template-formula.
$ git add TEMPLATE/files/default/example.tmpl
$ pre-commit run
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Ruby style with rubocop and rubocop-rspec......(no files to check)Skipped
Check shell scripts with shellcheck..................(no files to check)Skipped
Check YAML syntax with yamllint......................(no files to check)Skipped
Check Salt files using salt-lint.........................................Failed
- hook id: salt-lint
- exit code: 2

Examining /var/folders/cf/z8mkk4k56wgdq1r25qgtt_gc0000gn/T/tmpumnbj3tl.sls of type state
Examining TEMPLATE/files/default/example.tmpl of type state
[206] Jinja variables should have spaces before and after: {{ var_name }}
TEMPLATE/files/default/example.tmpl:6
{{ source}}
$ cat TEMPLATE/files/default/example.tmpl 
########################################################################
# File managed by Salt at <{{ source }}>.
# Your changes will be overwritten.
########################################################################

{{ source }}

This is an example file from SaltStack template-formula.
$ git add TEMPLATE/files/default/example.tmpl
$ git ci -m "A problematic commit message"   
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Ruby style with rubocop and rubocop-rspec......(no files to check)Skipped
Check shell scripts with shellcheck..................(no files to check)Skipped
Check YAML syntax with yamllint......................(no files to check)Skipped
Check Salt files using salt-lint.........................................Passed
Check commit message against @commitlint/config-conventional rules.......................Failed
- hook id: commitlint
- exit code: 1

⧗   input: A problematic commit message
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by dafyddj** [comment]
There is a conflict to resolve between the version of `@commitlint/config-conventional` used by `pre-commit` and the GitHub Action commitlint.

**Comment by dafyddj** [comment]
> There is a conflict to resolve between the version of `@commitlint/config-conventional` used by `pre-commit` and the GitHub Action commitlint.

I have pinned the version of `config-conventional` to `8.3.4` in this PR which is before the line length change upstream, and brings it into line with the version used in the wagoid GitHub action.

**Comment by dafyddj** [comment]
@myii do you agree that if we are going down the `pre-commit` route then it should also be run in CI, to keep versions etc. consistent?

**Comment by myii** [comment]
> > There is a conflict to resolve between the version of `@commitlint/config-conventional` used by `pre-commit` and the GitHub Action commitlint.
> 
> I have pinned the version of `config-conventional` to `8.3.4` in this PR which is before the line length change upstream, and brings it into line with the version used in the wagoid GitHub action.

@dafyddj Excellent, thanks.  That allows us to get this merged and have the discussion about commit title length (`72` => `100`)
 at a later time with the rest of the working group.

**Comment by myii** [comment]
> @myii do you agree that if we are going down the `pre-commit` route then it should also be run in CI, to keep versions etc. consistent?

@dafyddj I think that's an excellent idea, even if there's a bit of overlap with the other linters.  It is well worth seeing the output that users would see locally when the run `pre-commit`.

**Comment by dafyddj** [comment]
Ok - I actually meant instead of the other linters because they replicate each other at this point.

**Comment by dafyddj** [comment]
@myii Ready for review. Summary of latest changes:

- Dropped checks for whitespace (at least for now)
- run `pre-commit` in CI alongside current linters
- added a check for `reST` files
- simple `docs` fixes
- tidied up `pre-commit` usage instructions

**Comment by myii** [comment]
@dafyddj Any thoughts about automatically enabling `pre-commit` on repositories?

* https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

**Pull request merged**
