### PR TITLE
fix(comments): explain that at least an empty dict is required

### LINKED ISSUE #93: or {} changes don't work for me
The changes for default empty dictionary don't work for me,...

{%- import_yaml topdir ~ "/defaults.yaml" or {} as default_settings %}
{%- import_yaml topdir ~ "/osfamilymap.yaml" or {} as osfamilymap %}
{%- import_yaml topdir ~ "/osmap.yaml" or {} as osmap %}
{%- import_yaml topdir ~ "/osfingermap.yaml" or {} as osfingermap %}

do I need a special version of a component?

### PR DESCRIPTION
**Pull request by myii**
* For all `os*map.yaml` files
* Remove redundant `or {}` from `map.jinja`
* Close #93

---

See main discussion in #93.  Also links back to #59 and #60.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for the review, @n-rodriguez.

**Comment by daks** [comment]
So the conclusion is that `or {}` is not needed anymore? What was the problem then? Passing the data via `context` is sufficient?

It reminds me the first version of #60 :)

**Comment by myii** [comment]
@daks Here you go: https://github.com/saltstack-formulas/template-formula/issues/93#issuecomment-486099392.  I must have a very unique minion that works without the templates in place...!

**Comment by myii** [comment]
> It reminds me the first version of #60 :)

You didn't fight you case hard enough there, @daks!

**Comment by myii** [comment]
Thanks for the reviews, guys -- and for pointing out the error in the first place.

**Pull request merged**
