### PR TITLE
fix(convert-formula.sh): use portable `sed` function to make replacements

### LINKED ISSUE #192: [BUG] `convert-formula` calls ex with unknown argument
## Your setup

Host OS: Archlinux

### Formula commit hash / release tag
f48a7275644d2baef06adb0d8e74b3c19fd2d8a0

---

### Describe the bug
When running `bin/convert-formula.sh`, the following error occurs multiple times:

```
ex: illegal option -- u                                                                                              
Usage: ex [- | -s] [-l] [-L] [-R] [-r [file]] [-t tag]    
       [-v] [-V] [-w size] [+cmd | -c cmd] file...
```

The `-u` flag is not available in `ex` (or even `vi` as far as I can tell).

Debian-based systems tend to have `/usr/bin/ex` symlinked to `/usr/bin/vim.basic`, so the `-u` flag will work. But on my Arch box, `/usr/bin/ex` is the ex binary.

This error means that none of the search & replacements for `TEMPLATE` work.

### Steps to reproduce the bug

(On an Arch installation)
- Clone the formula repo locally
- cd into the formula directory
- Run `bin/convert-formula.sh example`

### Expected behaviour
`convert-formula.sh` should complete without errors and replace TEMPLATE strings correctly.

### Additional context

Maybe checking to see if `ex` is really vim in ex clothing, and then excluding the `-u` as required would fix it and not break any existing vim users.

### PR DESCRIPTION
**Pull request by dafyddj**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Fixes #192

### Describe the changes you're proposing

Use portable `sed` function to make text replacements.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Nice work, @dafyddj.  I'll probably get around to reviewing this sometime after tomorrow's meeting.

@stooj Would you mind testing this out to confirm that it fixes #192?

**Comment by myii** [comment]
Looks good on Arch Linux via. Docker (CC: @stooj):

```diff
# diff -r template-formula/ example-formula/
Only in template-formula/: AUTHORS.md
Only in template-formula/bin: convert-formula.sh
Only in template-formula/: CHANGELOG.md
Only in template-formula/docs: AUTHORS.rst
Only in template-formula/docs: CHANGELOG.rst
Only in template-formula/docs: conf.py
Only in template-formula/docs: CONTRIBUTING_DOCS.rst
Only in template-formula/docs: index.rst
diff -r template-formula/docs/README.rst example-formula/docs/README.rst
3c3
< TEMPLATE-formula
---
> example-formula
8c8
< .. |img_travis| image:: https://travis-ci.com/saltstack-formulas/TEMPLATE-formula.svg?branch=master
---
> .. |img_travis| image:: https://travis-ci.com/saltstack-formulas/example-formula.svg?branch=master
11c11
<    :target: https://travis-ci.com/saltstack-formulas/TEMPLATE-formula
---
>    :target: https://travis-ci.com/saltstack-formulas/example-formula
48,74c48
< .. <REMOVEME
<
< Using this template
< ^^^^^^^^^^^^^^^^^^^
<
< The easiest way to use this template formula as a base for a new formula is to use GitHub's **Use this template** button to create a new repository. For consistency with the rest of the formula ecosystem, name your formula repository following the pattern ``<formula theme>-formula``, where ``<formula theme>`` consists of lower-case alphabetic characters and numbers.
<
< In the rest of this example we'll use ``example`` as the ``<formula theme>``.
<
< Follow these steps to complete the conversion from ``template-formula`` to ``example-formula``. ::
<
<   $ git clone git@github.com:YOUR-USERNAME/example-formula.git
<   $ cd example-formula/
<   $ bin/convert-formula.sh example
<   $ git push --force
<
< Alternatively, it's possible to clone ``template-formula`` into a new repository and perform the conversion there. For example::
<
<   $ git clone https://github.com/saltstack-formulas/template-formula example-formula
<   $ cd example-formula/
<   $ bin/convert-formula.sh example
<
< To take advantage of `semantic-release <https://github.com/semantic-release/semantic-release>`_ for automated changelog generation and release tagging, you will need a GitHub `Personal Access Token <https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line>`_ with at least the **public_repo** scope.
<
< In the Travis repository settings for your new repository, create an `environment variable <https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings>`_ named ``GH_TOKEN`` with the personal access token as value, restricted to the ``master`` branch for security.
<
< .. REMOVEME>
---
> None
82c56
< ``TEMPLATE``
---
> ``example``
87,89c61,63
< This installs the TEMPLATE package,
< manages the TEMPLATE configuration file and then
< starts the associated TEMPLATE service.
---
> This installs the example package,
> manages the example configuration file and then
> starts the associated example service.
91c65
< ``TEMPLATE.package``
---
> ``example.package``
94c68
< This state will install the TEMPLATE package only.
---
> This state will install the example package only.
96c70
< ``TEMPLATE.config``
---
> ``example.config``
99c73
< This state will configure the TEMPLATE service and has a dependency on ``TEMPLATE.install``
---
> This state will configure the example service and has a dependency on ``example.install``
102c76
< ``TEMPLATE.service``
---
> ``example.service``
105c79
< This state will start the TEMPLATE service and has a dependency on ``TEMPLATE.config``
---
> This state will start the example service and has a dependency on ``example.config``
108c82
< ``TEMPLATE.clean``
---
> ``example.clean``
113c87
< this state will undo everything performed in the ``TEMPLATE`` meta-state in reverse order, i.e.
---
> this state will undo everything performed in the ``example`` meta-state in reverse order, i.e.
118c92
< ``TEMPLATE.service.clean``
---
> ``example.service.clean``
121c95
< This state will stop the TEMPLATE service and disable it at boot time.
---
> This state will stop the example service and disable it at boot time.
123c97
< ``TEMPLATE.config.clean``
---
> ``example.config.clean``
126,127c100,101
< This state will remove the configuration of the TEMPLATE service and has a
< dependency on ``TEMPLATE.service.clean`` via include list.
---
> This state will remove the configuration of the example service and has a
> dependency on ``example.service.clean`` via include list.
129c103
< ``TEMPLATE.package.clean``
---
> ``example.package.clean``
132,133c106,107
< This state will remove the TEMPLATE package and has a depency on
< ``TEMPLATE.config.clean`` via include list.
---
> This state will remove the example package and has a depency on
> ``example.config.clean`` via include list.
135c109
< ``TEMPLATE.subcomponent``
---
> ``example.subcomponent``
141c115
< configuring and starting the TEMPLATE service.
---
> configuring and starting the example service.
143c117
< ``TEMPLATE.subcomponent.config``
---
> ``example.subcomponent.config``
146,147c120,121
< This state will configure the TEMPLATE subcomponent and has a
< dependency on ``TEMPLATE.config`` via include list.
---
> This state will configure the example subcomponent and has a
> dependency on ``example.config`` via include list.
149c123
< ``TEMPLATE.subcomponent.config.clean``
---
> ``example.subcomponent.config.clean``
152,154c126,128
< This state will remove the configuration of the TEMPLATE subcomponent
< and reload the TEMPLATE service by a dependency on
< ``TEMPLATE.service.running`` via include list and ``watch_in``
---
> This state will remove the configuration of the example subcomponent
> and reload the example service by a dependency on
> ``example.service.running`` via include list and ``watch_in``
180c154
< Creates the docker instance and runs the ``TEMPLATE`` main state, ready for testing.
---
> Creates the docker instance and runs the ``example`` main state, ready for testing.
Only in template-formula/docs: _static
Only in example-formula/: example
diff -r template-formula/FORMULA example-formula/FORMULA
1c1
< name: TEMPLATE
---
> name: example
4c4
< version: 4.0.6
---
> version: 1.0.0
7c7
< summary: TEMPLATE formula
---
> summary: example formula
9c9
< top_level_dir: TEMPLATE
---
> top_level_dir: example

<< SNIP
(all `.git` diffs)
>> SNAP

diff -r template-formula/kitchen.yml example-formula/kitchen.yml
162c162
<   formula: TEMPLATE
---
>   formula: example
183c183
<             - TEMPLATE
---
>             - example
188c188
<               - TEMPLATE
---
>               - example
191c191
<         TEMPLATE.sls: pillar.example
---
>         example.sls: pillar.example
203c203
<             - TEMPLATE
---
>             - example
208c208
<               - TEMPLATE
---
>               - example
211c211
<         TEMPLATE.sls: test/salt/pillar/centos6.sls
---
>         example.sls: test/salt/pillar/centos6.sls
diff -r template-formula/pillar.example example-formula/pillar.example
4c4
< TEMPLATE:
---
> example:
36c36
<     #         I.e.: salt://TEMPLATE/files/default
---
>     #         I.e.: salt://example/files/default
44c44
<     #   TEMPLATE-config-file-file-managed:
---
>     #   example-config-file-file-managed:
50c50
<       TEMPLATE-config-file-file-managed:
---
>       example-config-file-file-managed:
52c52
<       TEMPLATE-subcomponent-config-file-file-managed:
---
>       example-subcomponent-config-file-file-managed:
diff -r template-formula/.rubocop.yml example-formula/.rubocop.yml
11,14d10
< # <REMOVEME
< Metrics/BlockLength:
<   Max: 36
< # REMOVEME>
Only in template-formula/: TEMPLATE
diff -r template-formula/test/integration/default/controls/config_spec.rb example-formula/test/integration/default/controls/config_spec.rb
3c3
< control 'TEMPLATE configuration' do
---
> control 'example configuration' do
27,28c27,28
<         '{"TEMPLATE-config-file-file-managed": ["example.tmpl.jinja"], '\
<         '"TEMPLATE-subcomponent-config-file-file-managed": '\
---
>         '{"example-config-file-file-managed": ["example.tmpl.jinja"], '\
>         '"example-subcomponent-config-file-file-managed": '\
diff -r template-formula/test/integration/default/controls/packages_spec.rb example-formula/test/integration/default/controls/packages_spec.rb
7c7
< control 'TEMPLATE package' do
---
> control 'example package' do
diff -r template-formula/test/integration/default/controls/services_spec.rb example-formula/test/integration/default/controls/services_spec.rb
7c7
< control 'TEMPLATE service' do
---
> control 'example service' do
diff -r template-formula/test/integration/default/controls/subcomponent_config_spec.rb example-formula/test/integration/default/controls/subcomponent_config_spec.rb
3c3
< control 'TEMPLATE subcomponent configuration' do
---
> control 'example subcomponent configuration' do
6c6
<   describe file('/etc/TEMPLATE-subcomponent-formula.conf') do
---
>   describe file('/etc/example-subcomponent-formula.conf') do
14c14
<         '<salt://TEMPLATE/subcomponent/config/files/default/'\
---
>         '<salt://example/subcomponent/config/files/default/'\
diff -r template-formula/test/integration/default/inspec.yml example-formula/test/integration/default/inspec.yml
5c5
< title: TEMPLATE formula
---
> title: example formula
8c8
< summary: Verify that the TEMPLATE formula is setup and configured correctly
---
> summary: Verify that the example formula is setup and configured correctly
diff -r template-formula/test/salt/pillar/centos6.sls example-formula/test/salt/pillar/centos6.sls
4c4
< TEMPLATE:
---
> example:
48c48
<       TEMPLATE-config-file-file-managed:
---
>       example-config-file-file-managed:
50c50
<       TEMPLATE-subcomponent-config-file-file-managed:
---
>       example-subcomponent-config-file-file-managed:
diff -r template-formula/.travis.yml example-formula/.travis.yml
108,122d107
<     # <REMOVEME
<
<     # Test the conversion of `template-formula` into another formula
<     # ready for development
<     - env: 'Conversion'
<       name: 'Test: bin/convert-formula.sh'
<       script:
<         - git clone . tmp/converted-formula
<         - cd tmp/converted-formula
<         - DEBUG=true bin/convert-formula.sh converted
<         - '[ $(git rev-list HEAD --count) -eq 2 ]'
<         # Quick visual check that correct files have been updated
<         - git show --pretty="" --name-status
<         - bin/kitchen verify default-debian-10-2019-2-py3
<     # REMOVEME>
```

**Comment by myii** [comment]
Diffing the diffs (comparing the `diff` output), before and after this PR, via. the `Use this template` button:

```diff
--- before
+++ after
@@ -231,13 +231,11 @@
 ---
 >       example-subcomponent-config-file-file-managed:
 diff -r template-formula/.rubocop.yml example-formula/.rubocop.yml
-11,14c11
+11,14d10
 < # <REMOVEME
 < Metrics/BlockLength:
 <   Max: 36
 < # REMOVEME>
----
-> 
 Only in template-formula/: TEMPLATE
 diff -r template-formula/test/integration/default/controls/config_spec.rb example-formula/test/integration/default/controls/config_spec.rb
 3c3
@@ -296,7 +294,7 @@
 ---
 >       example-subcomponent-config-file-file-managed:
 diff -r template-formula/.travis.yml example-formula/.travis.yml
-108,120d107
+108,122d107
 <     # <REMOVEME
 <
 <     # Test the conversion of `template-formula` into another formula
@@ -308,5 +306,7 @@
 <         - cd tmp/converted-formula
 <         - DEBUG=true bin/convert-formula.sh converted
 <         - '[ $(git rev-list HEAD --count) -eq 2 ]'
+<         # Quick visual check that correct files have been updated
+<         - git show --pretty="" --name-status
 <         - bin/kitchen verify default-debian-10-2019-2-py3
 <     # REMOVEME>
```

Interpretation:

* The second diff (`.travis.yml`) is part of this PR, so expected.
* The first diff (`.rubocop.yml`) is actually an _improvement_, since we're no longer left with an empty line at the end of the file, which triggers the `yamllint` violation:

```bash
example-formula$ yamllint -s .
./.rubocop.yml
  11:1      error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by myii** [comment]
Nice work @dafyddj -- merged.

**Comment by dafyddj** [comment]
Thanks - yes, this is a better implementation overall I think.

**Pull request merged**
