### PR TITLE
ci(platform): add `arch-base-latest`

### PR DESCRIPTION
**Pull request by myii**
* Automated using https://github.com/myii/ssf-formula/pull/40

### CODE REVIEW

**Comment by myii** [comment]
Self-merging so that this platform can be adopted in current and upcoming PRs, as required.

**Comment by noelmcloughlin** [comment]
@myii Should we use python3 for salt-bootstrap?
```
vagrant@archlinux:~$ python --version
Python 3.7.2
vagrant@archlinux:~$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by myii** [comment]
@noelmcloughlin [Quoting](https://freenode.logbot.info/saltstack-formulas/20190922#c2679402) @javierbertoli during our conversation on Slack:

> -|-|-
> :-:|---|---
> 14:07 | javier | @​noel.mcloughlin added ArchLinux images. My Arch-fu is 'this close to null', so I did my best :PAs I understand, there's only a single Arch image available in dockerhub. Also, the `saltbootstrap` script does not provide python3 installers on Arch, only `python2`, and there are no packages for Arch, so I created* netmanagers/salt-2017.7-py2:archlinux-base-latest* netmanagers/salt-2018.3-py2:archlinux-base-latest* netmanagers/salt-2019.2
> 14:07 | | :archlinux-base-latest

**Comment by myii** [comment]
@javierbertoli Actually, continuing from that quote above, I found there is a package for Salt on Arch Linux:

* https://www.archlinux.org/packages/?sort=&q=salt&maintainer=&flagged=

However, it appears to be only a single `salt` package, that installs _everything_.

**Comment by noelmcloughlin** [comment]
I use `sh bootstrap_salt.sh -x python3` and yes, it probably installs that package.

**Pull request merged**
