### PR TITLE
chore(defaults): add default retry dict (WIP)

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [x] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Let's add a retry Dict for fast implementation of retries.  SLS usage is:   

                         `retry: {{ TEMPLATE.retry_option }}`

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
It's appears as `retry_options` in [some formulas](https://github.com/search?q=org%3Asaltstack-formulas+retry_options&type=Code) but I always use `retry_option` because that's what the feature is called in [salt documentation](https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states). 

> The retry option in a state

From a state perspective, there is only one **retry option** not multiple **retry options.**

So the main question is whether `s` is preferred in this PR.

**Comment by noelmcloughlin** [comment]
And [some formulas](https://github.com/search?q=org%3Asaltstack-formulas+retry_option&type=Code) use `retry_option`

**Comment by daks** [comment]
If I understand it correctly this PR had a the option to run each state 3 times until it succeeds.

Not sure I'm in favour, a state should succeed at the first apply, if it does not I prefer to know it.
_(during some time, our kitchen setup also ran highstate twice because first one never succeeded. We didn't see the problems until we changed this setup)_

**Comment by noelmcloughlin** [comment]
This PR adds an example default implementation of salt requisites, retry:
https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
useful when a state author wants to add retry option to that state. Retries
are really useful for *archive.extracted* when source=internet, and during
development using hotel wifi ;-). I would use a retry option selectively.
Both retry>1 and retry=0 are both valid in reactive systems approach where
resilience is important, but this PR does not use or force the feature.

**Comment by daks** [comment]
So, this adds the default option but it still needs to be *explicitely* added to each state?

**Comment by noelmcloughlin** [comment]
Yes. But we could put the PR on hold. Maybe the template-formula should
include an example usage?

**Comment by noelmcloughlin** [comment]
Closing as stale.

**Pull request closed without merging**
