### PR TITLE
ci(proxy): allow rubygems proxy in gemfile

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

This PR allows environment look in Gemfile for  ` source` and falls back to rubygems.org

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by baby-gnu — APPROVED** [review]
I have nothing against this

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Thanks, @noelmcloughlin (and @baby-gnu for the review) -- merged.

This will be pushed out across repos using the `ssf-formula` soon.

**Comment by myii** [comment]
Pushed out across all formulas with @noelmcloughlin as the commit author using https://github.com/myii/ssf-formula/pull/408.

**Comment by noelmcloughlin** [comment]
Thanks @myii

**Pull request merged**
