### PR TITLE
refactor(tpldir): use `tpldir` or derivatives to make formula portable

### LINKED ISSUE #22: Formula based off template can't be moved from the root salt directory
The template assumes the formula will always live in salt://<formulaname> as noted here:

{% from "template/map.jinja" import template with context %}

It would be better to use: 

{% from tpldir ~ "/map.jinja" import template with context %}

### PR DESCRIPTION
**Pull request by myii**
* Close #22.

---

Adapted from the introduction in 068a94d (#28):
https://github.com/saltstack-formulas/template-formula/blob/068a94d3a242ec818640205626b011f8e53acf1a/template/macros.jinja#L46

### CODE REVIEW

**Comment by myii** [comment]
@vutny I'm particularly interested in applying this workaround/fix to the remaining files in `postgres-formula`, since most of the formula has been made portable.  What do you think?

**Comment by myii** [comment]
@aboe76 Thanks for the review.  Do you mind merging it?  Hopefully, @vutny and I can have the conversation over at the `postgres-formula`.

**Comment by aboe76** [comment]
@myii merged it

**Comment by myii** [comment]
On Sun, 24 Feb 2019 03:10:21 -0800, Niels Abspoel wrote:
> @myii merged it
>

@aboe76 Thanks, got another PR based on this branch which I'll send soon.

-- 
Sent using Dekko from my Ubuntu device

**Pull request merged**
