### PR TITLE
Use https in the link to SaltStack documentation

### PR DESCRIPTION
**Pull request by vutny**
It is always better to use `https` wherever possible.

@aboe76 Please, would you be able to merge this in? Thank you.

### CODE REVIEW

**Comment by vutny** [comment]
Since SaltStack merged PR saltstack/salt#46097, this could be brought in as well.
@noelmcloughlin could you please merge it?

**Comment by javierbertoli** [comment]
I'm not @noelmcloughlin, but I guess it's the same? :smile:
Thanks, @vutny

**Comment by vutny** [comment]
Awesome! You always just step in when I don't expect @javierbertoli :smile:

**Comment by javierbertoli** [comment]
:smile:

**Pull request merged**
