### PR TITLE
feat: add Gentoo support

### PR DESCRIPTION
**Pull request by myii**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

* Semi-automated using https://github.com/myii/ssf-formula/pull/268

### Describe the changes you're proposing

Make use of the new pre-salted images:

* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/55

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Review by baby-gnu — APPROVED** [review]
Nice way to extend the `systemd` InSpec library.

**Review by daks — APPROVED** [review]
Nice addition. Do you plan to add Gentoo to 'basic' testing on all formulas?

**Comment by myii** [comment]
Appreciate the review, @baby-gnu.

> ... Do you plan to add Gentoo to 'basic' testing on all formulas?

@daks Thanks for review, too.  The plan is to include it in the (commented out) platforms at the very least.  Hopefully, they can be enabled in formulas which have already been configured for use on Gentoo.

**Comment by myii** [comment]
Merging with two approvals, failures are due to Tiamat issues (unrelated to this PR).

**Pull request merged**
