### PR TITLE
docs(README): add authors.md

### PR DESCRIPTION
**Pull request by aboe76**
generated authors.md

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
I see `maintainer contributors` command generates this.  Is there a way to auto execute this command in a repo when doing a git commit or git push?

**Comment by myii** [comment]
@aboe76 Before finalising this, care to bump the changelog and `FORMULA` file (after #27 is merged)?

**Comment by myii** [comment]
> I see `maintainer contributors` command generates this. Is there a way to auto execute this command in a repo when doing a git commit or git push?

@noelmcloughlin I'm sure something useful can be done with a git hook, either the `pre-commit` or `pre-push` hook.  Worst case, it can at least prevent the commit/merge from completing until it ensures the authors file has been updated and included.

**Comment by aboe76** [comment]
@myii and @noelmcloughlin I generated these files with a container, not something you can do with a githook.

**Comment by myii** [comment]
@aboe76 Can't the repo be pulled into the container?

**Pull request merged**
