### PR TITLE
feat(kitchen+travis): conduct tests on a wider range of platforms

### PR DESCRIPTION
**Pull request by myii**
Based on discussions Slack/IRC/Matrix leading to [the following plan](https://freenode.logbot.info/saltstack-formulas/20190220#c2012702):

* Debian:
  - debian-9
  - debian-8
  - ubuntu-18
  - ubuntu-16
* RedHat:
  - centos-7
  - centos-6
  - fedora
* Suse:
  - opensuse

---

WIP because 6/8 are working (the other two have been commented out for now), so need to work out how we want to proceed.

### CODE REVIEW

**Comment by myii** [comment]
All 6+1 passing fine: https://travis-ci.com/saltstack-formulas/template-formula/builds/101711770.

**Comment by myii** [comment]
### Issues to resolve (or ignore)

#### `centos-6`

Not based on `systemd` so the current tests will always fail.  Either we rewrite the tests to work across all 8 platforms or we leave this commented out going forward.  I favour the latter, at least for this PR.

#### `opensuse`

Tried many of the `opensuse`-based docker images but ended up with the same SSH problem for every one of them:

```travis
       Step 17/17 : RUN echo ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQC86g3x8L72M/KTjYtuWehpQim7SU7gF6A1EAe5H7/FbE\+oOTs0Yy3Gj24I65BDa5sZfnAwxNYZW88MReFEM1e09sbsVZU\+1ypTlbTLj/HiVmRehZD77v2pSUatQ/m4zW4taTxoZ1Zm7hEPXPX7DPSm0rke2n3UMVn3AlapDxgmVP83Ko0b454XjwE7NEgFiQUfpHWjXzm0ioVB\+i75P9HdwfiB4jzM371dehaEgq3SanFe3wzR54C/LRqbXUrBIhOmR3wRc7739bbf/jt4kexQhDUZ4BIt9aEW6DNZfOxsq9CABTIPB2CUZmuJuZA5Z\+VHWY9cEynRpvZBhdV4LWHv\ kitchen_docker_key >> /home/kitchen/.ssh/authorized_keys
        ---> Running in d40ec41584dc
        ---> ead2693c2478
       Removing intermediate container d40ec41584dc
       Successfully built ead2693c2478
       2581c932e6287f2cef624d293d203a2d3050b39aaf19e738de1dca6fb08a4041
       0.0.0.0:32768
       Waiting for SSH service on localhost:32768, retrying in 3 seconds
       Waiting for SSH service on localhost:32768, retrying in 3 seconds
       Waiting for SSH service on localhost:32768, retrying in 3 seconds

       ... 

       Waiting for SSH service on localhost:32768, retrying in 3 seconds
       Waiting for SSH service on localhost:32768, retrying in 3 seconds
       Waiting for SSH service on localhost:32768, retrying in 3 seconds
$$$$$$ [SSH] connection failed, terminating (#<Errno::ECONNRESET: Connection reset by peer>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [SSH session could not be established] on default-opensuse
```

On a related note, `opensuse` is [deprecated](https://hub.docker.com/_/opensuse):

> DEPRECATED - for current images by the openSUSE Project see opensuse/leap and opensuse/tumbleweed.

* This is reason for using `opensuse/leap` for this PR.

**Comment by myii** [comment]
This still needs to be updated according to our final decisions:

https://github.com/saltstack-formulas/template-formula/blob/43bf1669fbc155968d10920cb0d83741836e82c2/test/integration/default/inspec.yml#L6-L9

---

Another idea to enable `centos-6`; perhaps use a conditional in:

* [`./test/integration/default/controls/services_spec.rb`](https://github.com/saltstack-formulas/template-formula/blob/43bf1669fbc155968d10920cb0d83741836e82c2/test/integration/default/controls/services_spec.rb)

---

Getting warnings from `travis lint`:

```ini
[x] unexpected key jobs, dropping
[x] value for env section is empty, dropping
[x] in env section: value for matrix section is empty, dropping
[x] in env.matrix section: unexpected pair
```

**Comment by myii** [comment]
https://kitchen.ci/docs/getting-started/kitchen-yml/:

> As of test-kitchen 1.21.0, we now prefer `kitchen.yml` over `.kitchen.yml`. This preference applies to `kitchen.local.yml` as well. This is backward compatible so the dot versions continue to work.

**Comment by myii** [comment]
After a [bunch of testing](https://freenode.logbot.info/saltstack-formulas/20190221#c2013796) involving @javierbertoli, @noelmcloughlin and some crucial help from @gtmanfred, we now have `opensuse-leap` working as well!

**Comment by myii** [comment]
Currently blocked by #41 -- after that is merged, this can be rebased.

**Comment by myii** [comment]
@aboe76 @javierbertoli I've removed the `WIP` tagging and believe this is ready for merge whenever you're ready.  A follow-on task would be to find a better solution for `centos-6`.

**Comment by aboe76** [comment]
@myii merged it

**Comment by myii** [comment]
@aboe76 Thanks.  I'll respond to [your comment](https://github.com/saltstack-formulas/template-formula/pull/28#discussion_r259582211) about the `systemd-formula` shortly.

**Pull request merged**
